# Generated by Django 2.2 on 2020-11-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='questionId',
            field=models.IntegerField(),
        ),
    ]
