# Generated by Django 2.2 on 2020-11-03 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='ans',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='question',
        ),
        migrations.AddField(
            model_name='quizz',
            name='name',
            field=models.CharField(default='no quiz', max_length=20),
        ),
        migrations.CreateModel(
            name='quizzQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('option1', models.CharField(max_length=30)),
                ('option2', models.CharField(max_length=30)),
                ('option3', models.CharField(max_length=30)),
                ('option4', models.CharField(max_length=30)),
                ('ans', models.CharField(max_length=300)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quizz')),
            ],
        ),
    ]
