# Generated by Django 2.2 on 2020-11-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20201105_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='no name', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='no pass', max_length=20),
        ),
    ]
