# Generated by Django 2.2 on 2020-11-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20201105_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('name', models.CharField(default='no name', max_length=20)),
                ('password', models.CharField(default='no pass', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='role',
        ),
    ]
