# Generated by Django 2.2 on 2020-11-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='questionId',
        ),
    ]
