# Generated by Django 2.2 on 2020-11-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_remove_answer_questionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='questionId',
            field=models.IntegerField(default=0),
        ),
    ]
