# Generated by Django 2.2 on 2020-11-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_answer_questionid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
