# Generated by Django 2.2 on 2020-11-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_delete_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
