# Generated by Django 2.2 on 2020-11-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20201106_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzquestion',
            name='studentAns',
            field=models.CharField(default='no', max_length=300),
        ),
    ]
